### ISSUE TITLE
Is there a way to set printer name

### ISSUE THREAD

**Issue by garyriet** [berrystephenw/OctoText#42] opened 2021-04-03 15:14 UTC
First off this plugin is AWESOME!!!!!!!!!!!!!!!!!!!!!

I have 9 printers is there a way to send the name of the printer if the TXT?
Thanks
Gary

**Comment by berrystephenw** [comment] 2021-04-03 19:56
I'm working on inserting the appearance name in the "From" line. It shouldn't take too much to get it done.

**Comment by garyriet** [comment] 2021-04-03 21:59
Even in the subject line. If I have time I will read the documentation on plugins

**Comment by berrystephenw** [comment] 2021-04-05 16:41
closing this issue because it's not a bug - but a feature request. It has been implemented in RC2.

**Closed by berrystephenw** 2021-04-05 16:41 UTC
