### ISSUE TITLE
Test message caused Octoprint to hang

### ISSUE THREAD

**Issue by gobbledygoober** [berrystephenw/OctoText#94] opened 2021-07-05 12:10 UTC
On first setup, I had trouble getting the Test message to send successfully. 

Octoprint would hang with no OctoText messages in octoprint.log with the default logging levels, requiring a restart off the service.

In the end, it turns out that I had the "Enable webcam snapshots" option ticked, and my camera was disconnected. 

After a service restart and unchecking the option, the Test message feature worked as expected. 

Can 1) a safe polling method for USB webcam that doesn't result in a hang and 2) a timeout be added to protect against other potential hangs?

I don't always have a camera connected so (1) would be a big help if normal (not Test) messages behave the same way. 

Thanks!

OctoPrint 1.6.1 
Python 3.7.3 
OctoPi 0.18.0
OctoText 0.3.1

**Comment by berrystephenw** [comment] 2021-07-05 12:50
Octoprint shouldn't hang when there isn't a webcam attached. It throws a ton of exceptions when you try to capture an image but it never hangs for me. Can you reproduce it again? Logs with debug mode enabled is helpful.

Thanks!

**Comment by gobbledygoober** [comment] 2021-07-05 14:32
Yep, I can reproduce it. Maybe it is a conflict with another plug-in. How does one enable debug logging? Are you interested in just ~/.octoprint/logs/octoprint.log ?

Thanks!

**Comment by berrystephenw** [comment] 2021-07-05 21:06
To enable logging you should go to Settings->logging, find octotext in the drop down menu https://user-images.githubusercontent.com/44931130/119266342-6ce11900-bbb8-11eb-8d1b-32195f36adcb.png
Then after you reproduce the issue you can send me octotext.log

**Comment by gobbledygoober** [comment] 2021-07-05 23:52
Understood. Thanks -- I will give this a shot later.

**Comment by gobbledygoober** [comment] 2021-07-06 01:42
Um, I do not seem to be generating any ~/.octoprint/logs/octotext.log after making my Logging page look just like that screenshot and clicking Save. 

I tried generating a Test message with working settings and got no file, then reproduced the issue again and confirmed no file afterwards. I waited 10 minutes then restarted the service. 

I see logging.yaml with:

```
loggers: 
  octoprint.plugins.OctoText:
    level: DEBUG
```

So I am fairly convinced that the settings have been applied. I see other logs in `logs` directory changing. 

No new octotext.log after the service restart either. 

Is there any other trick to getting the log to start? 

Thanks!

**Comment by berrystephenw** [comment] 2021-07-06 01:55
Sorry, my fault. I'm looking for the octoprint.log!

**Comment by gobbledygoober** [comment] 2021-07-06 03:40
Ah, thanks for clearing that up!

[octoprint_octotext.log](https://github.com/berrystephenw/OctoText/files/6767161/octoprint_octotext.log)

**Comment by berrystephenw** [comment] 2021-07-06 11:27
Interesting, not a single exception. Can you try this: temporarily disable all of your plugins except for Octotext and try it again. If it is an interaction with another plugin I will be able to reproduce it and then I'll have a shot at figuring out what is going on.

**Comment by gobbledygoober** [comment] 2021-07-06 13:14
Sure thing. I will try that in a bit. 

Should I leave any of the "default" plugins like the Announcement one enabled?

**Comment by berrystephenw** [comment] 2021-07-06 16:39
I'd leave the integrated plugins enabled. I test with a standard distribution and I'm trying to get your system to the same level first.

**Comment by gobbledygoober** [comment] 2021-07-07 01:50
I don't know what to say -- It is still happening with only the integration plugins enabled. 😕 

Things I have tried in desperation:

- In Settings -> Features -> Webcam and Timelapse -> Webcam -> Toggled "Enable webcam support" (no difference)
- In Settings -> Features -> Webcam and Timelapse -> Timelapse Recordings -> Snapshot URL test button (same URL used in OctoLapse, but timed out and printed exception in log)
```
2021-07-06 21:19:40,572 - octoprint.server.api - ERROR - Error while running a test GET request on http://127.0.0.1:8080/?action=snapshot
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 635, in _test_url
    method=method, url=url, timeout=timeout, verify=valid_ssl, stream=True
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=5.0)
```
- In Settings -> Features -> Webcam and Timelapse -> Timelapse Recordings -> Toggled "Enabled timelapse support" (no difference)
- Enabled octoprint DEBUG logger. Does not print any new hints and just shows when I restart the service:
```
2021-07-06 21:20:42,441 - octoprint.plugins.OctoText - DEBUG - The test button was pressed...
2021-07-06 21:20:42,443 - octoprint.plugins.OctoText - DEBUG - request = <OctoPrintFlaskRequest 'http://octopi/api/plugin/OctoText?%7B%22command%22:%22test%22,%22channel%22:null%7D' [GET]>
2021-07-06 21:20:42,444 - octoprint.plugins.OctoText - DEBUG - Sending text with image
2021-07-06 21:20:42,445 - octoprint.plugins.OctoText - DEBUG - Enable webcam setting True
2021-07-06 21:20:42,454 - octoprint.plugins.OctoText - DEBUG - filename for image: test-uSuTjSWwZaFNEZmv.jpg
2021-07-06 21:20:42,458 - octoprint.plugins.OctoText - DEBUG - Snapshot URL is: http://127.0.0.1:8080/?action=snapshot
2021-07-06 21:21:46,941 - octoprint.server - DEBUG - SIGTERM received...   <----------------------
```

What I haven't tried is, connecting a webcam and seeing if the behavior changes. I re-read my original post and I suppose I implied that I did that -- but I have not. 

Any other interesting logging levels to enable?

**Comment by berrystephenw** [comment] 2021-07-07 11:11
Just a nitpick, but Webcam and Timelapse isn't under Features correct? 

Enable Timelapse support has to be enabled or else it will never work. If you use the test button for snapshot URL you should see this when there is no camera (and the exceptions are expected - but nothing hangs for me): 
![image](https://user-images.githubusercontent.com/44931130/124748676-6650fb80-def1-11eb-9fd9-e27f5268a227.png)

All the code is doing is using the URL in the snapshot to fetch a screen shot. After that it uses ffmpeg to rotate and flip the image if you have told it to do so under the webcam settings. 

You can use another browser tab to check that octoprint doesn't hang when trying to fetch an image from the snapshot URL (I eventually get a connection reset in that tab). If it doesn't, and the test button doesn't return a dialog box then there is something very funky with your installation. 

Are you rotating/flipping the image? Is your path to ffmpeg correct?
Are you running octoprint in a docker or on a windows machine?

**Comment by gobbledygoober** [comment] 2021-07-08 15:15
> Just a nitpick, but Webcam and Timelapse isn't under Features correct?

I am a fellow nitpicker 😄 

I am away from home but this screenshot from the Spaghetti Detective website illustrates what I was referring to:
![EFD09AD2-0521-4A05-B615-528CA34EC054](https://user-images.githubusercontent.com/86916654/124946859-5d3d5880-dfdd-11eb-9480-6d28823cff81.jpeg)

But you are right -- confusingly there is a grey unclickable Features section (highlighted) and a clickable sub-section that is also called Features.  

> Enable Timelapse support has to be enabled or else it will never work. If you use the test button for snapshot URL you should see this when there is no camera (and the exceptions are expected - but nothing hangs for me)

Ok good. The Snapshot test URL button does not cause hangs for me either. 

> You can use another browser tab to check that octoprint doesn't hang when trying to fetch an image from the snapshot URL (I eventually get a connection reset in that tab).

This is indeed what happens on my system. Thanks for confirming. 

> Are you rotating/flipping the image? Is your path to ffmpeg correct?

I am using the latest OctoPi install and haven't changed the default settings for these options. I can verify that ffpmpeg is available when I get home. 

> Are you running octoprint in a docker or on a windows machine?

I don't think OctoPi uses docker, but I can check when I get back. 

Thanks!

**Comment by berrystephenw** [comment] 2021-07-09 11:55
if you aren't rotating the image then ffmpeg won't be used. Your screen shot shows avconv in place of ffmpeg - which I don't know anything about. 

I'm still not clear what hardware or environment you are running octoprint in. Are you using octoprint in a windows environment?

**Comment by gobbledygoober** [comment] 2021-07-09 15:32
@berrystephenw I am running on a Raspberry Pi 3B. The official [OctoPi](https://github.com/guysoft/OctoPi) image doesn't appear to be using docker.  

The screenshot was actually from the Spaghetti Detective's website — I was away from the network where OctoPrint was running and it happened to (mostly) illustrate what I was talking about. 

Thanks for explaining the dependency on ffmpeg. For grins, I confirmed that it was available on my system.

**Comment by berrystephenw** [comment] 2021-07-09 16:32
Ok so that makes sense. I still don't know why your image is hanging. I explicitly trap exceptions when accessing a webcam that isn't attached and send a generic webcam offline jpg instead. 

The only thing I can suggest at this point is to try burning a clean image and only load octotext and see if you still have a problem. If I can't reproduce the issue it is nearly impossible for me to debug and fix it. 

Another thought - did you customize the raspi-config when you created your image?

**Comment by gobbledygoober** [comment] 2021-07-10 00:39
I do not have another SD card handy, so I will have to backup my current one and start fresh. 

I did not customize anything in raspi-config except for the locale/keyboard info. 

Have you tested with the latest vanilla OctoPi image? That is what I would be trying. 

Thanks for the update.

**Comment by berrystephenw** [comment] 2021-07-10 10:31
My development environment is on a Windows machine and I test against the latest release as well as unreleased branches. I also run on 3 different Pi's, a 3, 4 and a compute module based system. There are no cam issues on those. 

The Python code communicates with the front end web server by sending a URL request to the snapshot address. Since the snapshot works when your camera is attached I can assume the code is working. What is confusing is that it isn't throwing an exception when there isn't a camera. It's behavior that is inconsistent with my testing. Most of my testing is done without a camera and the exception is caught correctly.

**Comment by gobbledygoober** [comment] 2021-07-13 11:21
Apologies for the silence. I was slowly troubleshooting my issue in discussion https://github.com/berrystephenw/OctoText/discussions/93 until yesterday. 

> The Python code communicates with the front end web server by sending a URL request to the snapshot address. Since the snapshot works when your camera is attached I can assume the code is working.

Do you know what the built-in OctoPrint Snapshot Test button does differently? That returns without issue when the camera is unplugged. 

I don't have another SD card and I am a little reluctant to backup/wipe, start fresh, troubleshoot, and eventually restore my current image, and so I was wondering first if  ...

Can I backup and temporarily add extra logging to `/home/pi/oprint/lib/python3.7/site-packages/octoprint_OctoText/__init__.py` to figure out exactly where things are not throwing an exception? 

I have never tinkered with plugins in OctoPrint but am somewhat Python literate and don't know if this would work the way I expect, or if extra steps are required for that to work. 

Thanks for sticking with this despite the trickle of revealing information.

**Comment by berrystephenw** [comment] 2021-07-13 12:35
If you set up a development environment that can reproduce the problem you would have a much better chance at figuring out the problem than extra logging. I say this because a lock up is something that is probably happening in the OctoPrint core code since I'm using standard library calls and not doing anything crazy with the code.
The likely section where something is going bad is here: https://github.com/berrystephenw/OctoText/blob/8d255e1447a080cbf5b5bd498faf54b79f33d7bf/octoprint_OctoText/__init__.py#L298-L342
and you can see I'm trapping any exceptions and logging what went wrong - those aren't appearing in the log file, so what ever is going on it's either never getting to the code to log the event, or the Pi is locked up doing something else. 
You can clone the project and fool around with logging if you like, but an IDE like PyCharm is fantastic at finding bugs like this. I can stop the process while it's locked up and step through the code to see what it is doing. 
Another option is that you can image the SD card and upload it to a shared cloud drive and I can copy it to an SD card and run the application that you are running and hopefully make some progress. You could also use it as a backup copy.

**Comment by cp2004** [comment] 2021-09-29 20:10
Checking out this plugin to see what else it does, and came across this issue. I know it's old, but I couldn't help but point out the problem!

When you call `requests.get`, if you don't specify a timeout then it will block and hang forever. Usually this is not a problem as the webcam service might return a 503 when it is not running, but maybe for some reason it is just hanging on the request in this case.

See this part of the requests docs, about always specifying a timeout in production code:

https://docs.python-requests.org/en/master/user/quickstart/#timeouts

Hope that helps 🙂

**Comment by berrystephenw** [comment] 2021-09-29 21:03
Thanks Charlie, looks like an easy fix. I’ll put it in next release.

Steve

Stephen Berry
Hardware Engineering Manager
GSSI
40 Simon St
Nashua, NH 03060
________________________________

**Comment by gobbledygoober** [comment] 2021-10-02 17:15
Nice work!

Good timing! I recently ponied up the cost of a 2nd micro SD card. 

I was curious if the base OctoPi image and *only* the OctoText plugin installed would behave any different than the card I was using before (with a dozen or so disabled plugins + OctoText). 

I tried without a webcam connected. It did behave differently. 

It worked as expected, with no hang. So it would seem that there is some incompatibility with another plugin that is causing that blocking `requests.get` to never return. 

In my spare time (sarcasm), I'd like to do a binary search of sorts and install half of the plugins, retry, and find the problematic combination of plugins. 

One related quirk to report: I left `Enable Webcam Snapshots` ticked and, even though I *did* receive the sample text message, this toast/notification appeared in OctoPrint that implied it failed:

![8A2B03D8-D068-4607-9953-5BA754ED27D6](https://user-images.githubusercontent.com/86916654/135726122-0a3cc3ca-0d86-49d9-97cf-dd88d0d7a34a.jpeg)

The text message included a "webcam offline" image as well.

With the option unchecked, an appropriate notification was presented:

![66D97D0B-ADDF-44CC-91CB-A2BEE3CCDABC](https://user-images.githubusercontent.com/86916654/135726124-37b76a18-7457-4555-a98c-48b49eaf5493.jpeg)

In this case, no image was attached.

**Comment by berrystephenw** [comment] 2021-12-17 01:15
Apologies for the long delay, I pushed the fix in the RC branch today. When you get a chance (if you are still using the plugin) please give it a try. 
I've also noticed the problem you reported above with the webcam not being enabled. I'll work on that next.

**Comment by berrystephenw** [comment] 2022-03-25 13:40
these issues should be fixed with the last release. If not let me know and I'll reopen the issue.

**Closed by berrystephenw** 2022-03-25 13:40 UTC
Labels: bug
